# Dependabot dependency version checks / updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
  - package-ecosystem: "cargo"
    directory: "/"
    versioning-strategy: "widen"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
